### ISSUE TITLE
unit test test_constructor_InstantiationWithDuplicatedSubscribers_ThrowsException

### ISSUE THREAD

**Issue by jonathan-letourneur** [jonathan-letourneur/GPR1-SocialNetwork#1]
le test unitaire test_constructor_InstantiationWithDuplicatedSubscribers_ThrowsException génère actuellement une erreur sur le dernier commit. J'ai essayé de corriger le commit 'https://github.com/jonathan-letourneur/GPR1-SocialNetwork/commit/6f1a9044528fbfd77965a42d5969bcc9eb5fa22b'. Je penses que les erreur proviennent de la classe observer

**Comment by NicolasGlassey** [comment]
@jonathan-letourneur 

Bonjour Jonathan,

J'ai pris en compte cette issue pour l'évaluation.

Bonne suite de week-end !
